export const linksCategories = ["global search"];
export const FiltersNames = [
  "home",
  "arts",
  "automobiles",
  "books",
  "business",
  "fashion",
  "health",
  "food",
  "insider",
  "movies",
  "obituaries",
  "opinion",
  "politics",
  "science",
  "sports",
  "technology",
  "upshot",
  "world",
];
